# Generated by Django 2.2.6 on 2022-02-03 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenreChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='multipleChoiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorquestion', models.CharField(db_index=True, max_length=240)),
                ('objectquestion', models.CharField(db_index=True, max_length=240)),
                ('genrequestion', models.CharField(db_index=True, max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectRecognitionTestNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_choices', models.ManyToManyField(to='predictors.ObjectChoices')),
                ('test_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='predictors.Test')),
            ],
        ),
        migrations.CreateModel(
            name='GenreTestNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_choices', models.ManyToManyField(to='predictors.GenreChoices')),
                ('test_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='predictors.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(db_index=True, max_length=240)),
                ('genre_test', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='predictors.GenreTestNew')),
                ('object_test', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='predictors.ObjectRecognitionTestNew')),
            ],
        ),
    ]
