# Generated by Django 2.2.6 on 2022-02-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='genre_test',
        ),
        migrations.AddField(
            model_name='answer',
            name='genre_test',
            field=models.ManyToManyField(to='predictors.GenreTestNew'),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='object_test',
        ),
        migrations.AddField(
            model_name='answer',
            name='object_test',
            field=models.ManyToManyField(to='predictors.ObjectRecognitionTestNew'),
        ),
    ]
