# Generated by Django 2.2.6 on 2022-03-03 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0003_auto_20220204_1305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenreChoices',
            new_name='GenreChoice',
        ),
        migrations.RenameModel(
            old_name='ObjectChoices',
            new_name='ObjectChoice',
        ),
    ]
