# Generated by Django 2.2.6 on 2022-03-03 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0004_auto_20220303_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ColorTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_choices', models.ManyToManyField(to='predictors.ColorChoice')),
                ('test_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='predictors.Test')),
            ],
        ),
    ]
