# Generated by Django 2.2.6 on 2022-03-03 18:27

#import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0005_colorchoice_colortest'),
    ]

  #  operations = [
   #     migrations.AlterField(
    #        model_name='colorchoice',
     #       name='color',
      #      field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
       # ),
    #]
