# Generated by Django 2.2.6 on 2022-03-03 18:33

#import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0006_auto_20220303_1827'),
    ]

   # operations = [
    #    migrations.AlterField(
     #       model_name='colorchoice',
      #      name='color',
       #     field=colorfield.fields.ColorField(choices=[('#FFFFFF', 'white'), ('#000000', 'black')], default='#FFFFFF', image_field=None, max_length=18, samples=None),
        #),
    #]
