# Generated by Django 2.2.6 on 2022-03-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0007_auto_20220303_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominant_color', models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue')], max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='colorchoice',
            name='color_image',
            field=models.ImageField(default=0, upload_to='colors_to_choose/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colorchoice',
            name='color',
            field=models.CharField(max_length=300),
        ),
    ]
