# Generated by Django 2.2.6 on 2022-03-04 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0008_auto_20220304_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorchoice',
            name='main_color',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='predictors.MainColor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maincolor',
            name='dominant_color',
            field=models.CharField(max_length=30),
        ),
    ]
