# Generated by Django 2.2.6 on 2022-03-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0009_auto_20220304_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincolor',
            name='dominant_color',
            field=models.CharField(choices=[('R', 'Red'), ('G', 'Green'), ('B', 'Blue')], max_length=30),
        ),
    ]
