# Generated by Django 2.2.6 on 2022-03-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0010_auto_20220304_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='colortest',
            name='color_answer',
            field=models.CharField(db_index=True, default=0, max_length=240),
            preserve_default=False,
        ),
    ]
