# Generated by Django 2.2.6 on 2022-03-06 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0013_auto_20220306_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='predictors.Test')),
            ],
        ),
        migrations.RemoveField(
            model_name='genreanswer',
            name='genre_test',
        ),
        migrations.RemoveField(
            model_name='objectanswer',
            name='object_test',
        ),
        migrations.RemoveField(
            model_name='colortest',
            name='color_choices',
        ),
        migrations.RemoveField(
            model_name='genretestnew',
            name='genre_choices',
        ),
        migrations.RemoveField(
            model_name='objectrecognitiontestnew',
            name='object_choices',
        ),
        migrations.AddField(
            model_name='colorchoice',
            name='color_question',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='predictors.ColorTest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genrechoice',
            name='genre_question',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='predictors.GenreTestNew'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectchoice',
            name='object_question',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='predictors.ObjectRecognitionTestNew'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ColorAnswer',
        ),
        migrations.DeleteModel(
            name='GenreAnswer',
        ),
        migrations.DeleteModel(
            name='ObjectAnswer',
        ),
    ]
