# Generated by Django 2.2.6 on 2022-03-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0014_auto_20220306_1645'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColorTest',
            new_name='ColorQuestion',
        ),
        migrations.RenameModel(
            old_name='GenreTestNew',
            new_name='GenreQuestion',
        ),
        migrations.RenameModel(
            old_name='ObjectRecognitionTestNew',
            new_name='ObjectQuestion',
        ),
    ]
