# Generated by Django 2.2.6 on 2022-03-07 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0015_auto_20220306_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='answers_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='predictors.Test')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_topic', models.CharField(choices=[('Genre', 'Genre'), ('Object', 'Object'), ('Color', 'Color')], max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='colorquestion',
            name='test_id',
        ),
        migrations.RemoveField(
            model_name='genrechoice',
            name='genre_question',
        ),
        migrations.RemoveField(
            model_name='genrequestion',
            name='test_id',
        ),
        migrations.RemoveField(
            model_name='objectchoice',
            name='object_question',
        ),
        migrations.RemoveField(
            model_name='objectquestion',
            name='test_id',
        ),
        migrations.DeleteModel(
            name='ColorChoice',
        ),
        migrations.DeleteModel(
            name='ColorQuestion',
        ),
        migrations.DeleteModel(
            name='GenreChoice',
        ),
        migrations.DeleteModel(
            name='GenreQuestion',
        ),
        migrations.DeleteModel(
            name='ObjectChoice',
        ),
        migrations.DeleteModel(
            name='ObjectQuestion',
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='predictors.QuestionTopic'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='predictors.Question'),
        ),
    ]
