# Generated by Django 2.2.6 on 2022-03-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0016_auto_20220307_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, upload_to='answers_images/'),
        ),
        migrations.AlterField(
            model_name='questiontopic',
            name='selected_topic',
            field=models.CharField(max_length=30),
        ),
    ]
