# Generated by Django 2.2.6 on 2022-03-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0019_objectoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_name', models.CharField(max_length=300)),
                ('art_style', models.CharField(max_length=300)),
            ],
        ),
    ]
