# Generated by Django 2.2.6 on 2022-03-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0020_genreoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork_name', models.CharField(max_length=300)),
                ('color_one', models.CharField(max_length=300)),
                ('color_two', models.CharField(max_length=300)),
                ('color_three', models.CharField(max_length=300)),
                ('color_one_coefficient', models.FloatField()),
                ('color_two_coefficient', models.FloatField()),
                ('color_three_coefficient', models.FloatField()),
            ],
        ),
    ]
