# Generated by Django 2.2.6 on 2022-04-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0022_result_found_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='coloroption',
            name='colors1_rgb',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coloroption',
            name='colors1_rgb_list',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coloroption',
            name='colors2_rgb',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coloroption',
            name='colors2_rgb_list',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coloroption',
            name='colors3_rgb',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coloroption',
            name='colors3_rgb_list',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
