# Generated by Django 2.2.6 on 2022-04-07 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0023_auto_20220407_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coloroption',
            name='colors1_rgb',
        ),
        migrations.RemoveField(
            model_name='coloroption',
            name='colors2_rgb',
        ),
        migrations.RemoveField(
            model_name='coloroption',
            name='colors3_rgb',
        ),
    ]
