# Generated by Django 2.2.6 on 2022-04-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0024_auto_20220407_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='coloroption',
            name='url',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
