# Generated by Django 4.0.4 on 2022-04-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0025_coloroption_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Object_Name_1', models.CharField(max_length=300)),
                ('Object_Name_2', models.CharField(max_length=300)),
                ('object_relations', models.FloatField()),
            ],
        ),
    ]
