# Generated by Django 2.2.6 on 2022-04-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0027_result_recommendation_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='color_score',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='genre_score',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='object_score',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
