# Generated by Django 2.2.6 on 2022-06-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0029_artworkinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkinfo',
            name='people_english',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
