# Generated by Django 2.2.6 on 2022-06-05 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0030_artworkinfo_people_english'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='genre_score',
        ),
        migrations.RemoveField(
            model_name='result',
            name='id',
        ),
        migrations.AddField(
            model_name='result',
            name='artwork_information',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='predictors.ArtworkInfo'),
            preserve_default=False,
        ),
    ]
