# Generated by Django 2.2.6 on 2022-06-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0031_auto_20220605_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='artwork_information',
        ),
        migrations.AddField(
            model_name='result',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
