# Generated by Django 2.2.6 on 2022-06-05 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0033_result_artwork_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='artwork_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='predictors.ArtworkInfo'),
        ),
    ]
